-- @description RS5k tools
-- @version 1.13
-- @author MPL
-- @website http://forum.cockos.com/showthread.php?t=188335
-- @metapackage
-- @provides
--    mpl_RS5k tools.lua
--    [main] mpl_RS5k tools/mpl_Add or replace source of item under mouse cursor for RS5k instance on selected track.lua
--    [main] mpl_RS5k tools/mpl_Add or replace source of selected item for RS5k instance on its track.lua
--    [main] mpl_RS5k tools/mpl_Add or replace source of selected item for RS5k instance on selected track.lua
--    [main] mpl_RS5k tools/mpl_Add or replace source of selected item for RS5k instance on track under mouse cursor.lua
--    [main] mpl_RS5k tools/mpl_Explode selected track RS5k instances to new tracks.lua
--    [main] mpl_RS5k tools/mpl_Export selected item to RS5k instance on same track as chromatic source.lua
--    [main] mpl_RS5k tools/mpl_Export selected items to RS5k instances on selected track (drum mode).lua
--    [main] mpl_RS5k tools/mpl_Export selected items to RS5k instances on selected track (use original source).lua
--    [main] mpl_RS5k tools/mpl_Export selected items to RS5k instances on selected track.lua
--    [main] mpl_RS5k tools/mpl_Export selected items to single RS5k instance on selected track.lua
--    [main] mpl_RS5k tools/mpl_Float RS5k related to input note on last touched track.lua
--    [main] mpl_RS5k tools/mpl_List next sample in directory for focused RS5k.lua
--    [main] mpl_RS5k tools/mpl_List next sample in directory for RS5k on selected track.lua
--    [main] mpl_RS5k tools/mpl_List previous sample in directory for focused RS5k.lua
--    [main] mpl_RS5k tools/mpl_List previous sample in directory for RS5k on selected track.lua
--    [main] mpl_RS5k tools/mpl_List random sample in directory for focused RS5k.lua
--    [main] mpl_RS5k tools/mpl_List samples in directory for focused RS5k (MIDI, OSC, Mousewheel).lua
--    [main] mpl_RS5k tools/mpl_Open and Close Media Explorer when single item is inserted, export chromatically to RS5k (background).lua
--    [main] mpl_RS5k tools/mpl_Open and Close Media Explorer when single item is inserted, export it to RS5k (background).lua
--    [main] mpl_RS5k tools/mpl_Reverse focused RS5k instance sample.lua
--    [main] mpl_RS5k tools/mpl_Collect and replace selected tracks RS5k instances samples into project folder.lua
--    [main] mpl_RS5k tools/mpl_Export selected Media Explorer items to RS5k instances on selected track (use original source).lua
--    [main] mpl_RS5k tools/mpl_Add note into RS5k instance name on selected track.lua
--    [main] mpl_RS5k tools/mpl_Sort by note start RS5k instances on selected track.lua
-- @changelog
--    # List next,previous,random sample in directory for focused RS5k avoid non-media extension
