-- @description ReaEQ tools
-- @version 1.01
-- @author MPL
-- @website http://forum.cockos.com/showthread.php?t=188335
-- @metapackage
-- @provides
--    [main] mpl_ReaEQ tools/mpl_Build harmonic series bands for focused ReaEQ.lua
--    [main] mpl_ReaEQ tools/mpl_Port focused ReaEQ bands to spectral edits on selected items.lua
--    [main] mpl_ReaEQ tools/mpl_Scale focused ReaEQ bands gain down.lua
--    [main] mpl_ReaEQ tools/mpl_Scale focused ReaEQ bands gain up.lua
--    [main] mpl_ReaEQ tools/mpl_Solo last touched ReaEQ band (alter).lua
--    [main] mpl_ReaEQ tools/mpl_Solo last touched ReaEQ band.lua
--    [main] mpl_ReaEQ tools/mpl_Sort focused ReaEQ bands by frequency.lua
--    [main] mpl_ReaEQ tools/mpl_Split focused ReaEQ to LR routing.lua
--    [main] mpl_ReaEQ tools/mpl_Toggle 64x oversampling for all ReaComp instances.lua