-- @description Pooled FX tools
-- @version 1.04
-- @author MPL
-- @website https://forum.cockos.com/showthread.php?t=188335
-- @provides
--    mpl_Pooled FX tools.lua
--    [main] mpl_Pooled FX tools/mpl_Set selected track as pooled fx master (group 1).lua
--    [main] mpl_Pooled FX tools/mpl_Add pooled fx slave JSFX to selected tracks at chain end.lua
--    [main] mpl_Pooled FX tools/mpl_Add pooled fx slave JSFX to selected tracks at chain start.lua
--    [main] mpl_Pooled FX tools/mpl_Propagate pooled FX (group 1).lua
--    [main] mpl_Pooled FX tools/mpl_Propagate last touched parameter to all pooled FX parameters.lua
--    [main] mpl_Pooled FX tools/mpl_Propagate pooled FX master parameters to all slaves (group 1).lua
--    [main] mpl_Pooled FX tools/mpl_Propagate pooled FX master bypass states to all slaves (group 1).lua
--    [main] mpl_Pooled FX tools/mpl_Propagate last touched pooled FX parameters to all pooled FX in group (group 1).lua
-- @changelog
--    #fix Propagate last touched pooled FX parameters to all pooled FX in group
